#define CRIME_GUNSHOTS "Gunshots"
#define CRIME_FIREFIGHT "Firefight"
#define CRIME_MURDER "Murder"
#define CRIME_BURGLARY "Burglary"
#define CRIME_EMERGENCY "Emergency Alarm"
#define CRIME_ATM_TAMPERING "Atm Tampering"
