#define NETWORK_POLICE "Police Network"
#define NETWORK_CLINIC "Clinic Network"
#define NETWORK_MILITARY "Military Network"
#define NETWORK_CAMARILLA "Tower Network"
#define NETWORK_ANARCH "Bar Network"
#define NETWORK_ENDRON "Endron Network"
